service: quarterback-spy

custom:
  ENV: prod
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.7
  profile: personal
  stage: ${self:custom.ENV}
  region: us-east-1

functions:
  poll:
    handler: lambda.handler
    environment:
      ENV: ${self:custom.ENV}
      SEATGEEK_API_KEY: ${file(prod.env.yml):SEATGEEK_API_KEY}
      SEATGEEK_EVENT_ID: ${file(prod.env.yml):SEATGEEK_EVENT_ID}
      SLACK_API_KEY: ${file(prod.env.yml):SLACK_API_KEY}
      SLACK_CHANNEL: ${file(prod.env.yml):SLACK_CHANNEL}
      MAX_AFFORDABLE_PRICE: ${file(prod.env.yml):MAX_AFFORDABLE_PRICE}
    events:
      - schedule: rate(5 minutes)

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**
