service: quarterback-spy

provider:
  name: aws
  runtime: python3.7
  profile: personal
  stage: prod
  region: us-east-1

functions:
  poll:
    handler: lambda.handler
    environment:
      ENV: prod
      SEATGEEK_API_KEY: ${ssm:SEATGEEK_API_KEY}
      SLACK_API_KEY: ${ssm:SLACK_API_KEY}
      SLACK_CHANNEL: ${ssm:SLACK_CHANNEL}
      MAX_AFFORDABLE_PRICE: ${ssm:MAX_AFFORDABLE_PRICE}
    events:
      - schedule: rate(10 minutes)
